kind: Deployment
apiVersion: apps/v1
metadata:
  name: websocket-server
  labels:
    app: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        image: registry.platform.tatar.ru/public/websocket-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8765
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: false
---
kind: Service
apiVersion: v1
metadata:
  name: websocket-server
  labels:
    app: websocket-server
spec:
  ports:
  - name: app-port
    protocol: TCP
    port: 8765
    targetPort: 8765
  selector:
    app: identity
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: websocket-client
  labels:
    app: websocket-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websocket-client
  template:
    metadata:
      labels:
        app: websocket-client
    spec:
      containers:
      - name: websocket-client
        image: registry.platform.tatar.ru/public/websocket-client:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: false
